inherit_from:
  - .rubocop_todo.yml

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 160
  IgnoredPatterns:
    - 'http:\/\/'
  AllowHeredoc: true
  AllowURI: true

Style/Documentation:
  Enabled: false
