Layout/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false

AllCops:
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
